# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.



default: &default

  keys:
    facebook_oauth:
      facebook_app_id: <% ENV['FACEBOOK_APP_ID'] %>
      facebook_app_secret: <% ENV['FACEBOOK_APP_SECRET'] %>

  mail_sender: <% ENV['DEFAULT_FROM_EMAIL'] %>

development:
  << : *default
  secret_key_base: d6ace61cbf05b52044d1072d6a8dd025fc4d95071f2d7a432e705de05dfa0613c0cb00759c4356ab74511b2968f62245fccc101618899ae2cc3c3e8c41b3aa8c

test:
  << : *default
  secret_key_base: b8bb9776e0986f0e9b6589a205b935e056c85ba454221fc2fb0cfb2325a446cbb5aca60a63f88ac9004e25eacbbaaf07cb8b974fe6db553065f4261b19e89797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  << : *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
